#!/usr/bin/env python3
"""Build compact JS star/constellation/milky-way data for stars.tannerwj.com.

Inputs (in ../data/):
  hyg_v44.csv.gz      - HYG Stellar Database v4.4 (Hipparcos/Yale/Gliese), Astronexus
  conlines.json       - IAU constellation line figures (d3-celestial, Olaf Frohn)
  mw.json             - Milky Way outline polygons (d3-celestial, Olaf Frohn)
Outputs (in ../public/js/):
  data-stars.js       - FIELD Float32Array [raRad, decRad, mag, bv] (mag<=6.5)
                        + NAMED array of [name, raRad, decRad, mag, bv, desig, distLy]
  data-con.js         - constellation segments + a few label anchors
  data-mw.js          - simplified Milky Way glow polygons
"""
import csv, gzip, json, math, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, '..', 'data')
OUT = os.path.join(HERE, '..', 'public', 'js')
os.makedirs(OUT, exist_ok=True)

GREEK = {'Alp':'\u03b1','Bet':'\u03b2','Gam':'\u03b3','Del':'\u03b4','Eps':'\u03b5','Zet':'\u03b6',
         'Eta':'\u03b7','The':'\u03b8','Iot':'\u03b9','Kap':'\u03ba','Lam':'\u03bb','Mu':'\u03bc',
         'Nu':'\u03bd','Xi':'\u03be','Omi':'\u03bf','Pi':'\u03c0','Rho':'\u03c1','Sig':'\u03c3',
         'Tau':'\u03c4','Ups':'\u03c5','Phi':'\u03c6','Chi':'\u03c7','Psi':'\u03c8','Ome':'\u03c9'}

SPEC_BV = {'O':-0.30,'B':-0.15,'A':0.10,'F':0.35,'G':0.60,'K':0.95,'M':1.45,
           'W':-0.25,'C':1.2,'S':1.2,'D':0.1,'L':1.6,'T':1.8,'Y':2.0}

def bv_from(spect, ci):
    try:
        v = float(ci)
        if -0.5 < v < 3.0:
            return v
    except (TypeError, ValueError):
        pass
    if spect:
        return SPEC_BV.get(spect.strip()[0].upper(), 0.3)
    return 0.3

def designation(bayer, flam, con):
    con = (con or '').strip()
    b = (bayer or '').strip()
    f = (flam or '').strip()
    if b and b in GREEK and con:
        return GREEK[b] + ' ' + con
    if f and con:
        return f + ' ' + con
    if con:
        return 'HR?' 
    return ''

def main():
    field = []   # [raRad, decRad, mag, bv]
    named = []   # [name, raRad, decRad, mag, bv, desig, distLy]
    n_named_proper = 0
    with gzip.open(os.path.join(DATA, 'hyg_v44.csv.gz'), 'rt') as f:
        for row in csv.DictReader(f):
            if row['id'] == '0':
                continue  # Sol
            try:
                mag = float(row['mag'])
            except ValueError:
                continue
            if mag > 6.5:
                continue
            try:
                ra_h = float(row['ra']); dec_d = float(row['dec'])
            except ValueError:
                continue
            ra = ra_h * 15.0 * math.pi / 180.0
            dec = dec_d * math.pi / 180.0
            bv = bv_from(row.get('spect'), row.get('ci'))
            field.append((round(ra, 4), round(dec, 4), round(mag, 2), round(bv, 2),
                          int(row['hip']) if (row.get('hip') or '').strip().isdigit() else 0))
            proper = (row.get('proper') or '').strip()
            if proper:
                n_named_proper += 1
                try:
                    dist_pc = float(row.get('dist') or 0)
                except ValueError:
                    dist_pc = 0
                dist_ly = round(dist_pc * 3.26156, 1) if dist_pc > 0 else 0
                named.append([proper, round(ra, 4), round(dec, 4), round(mag, 2),
                              round(bv, 2), designation(row.get('bayer'), row.get('flam'), row.get('con')), dist_ly,
                              (row.get('spect') or '').strip()[:8]])
    print(f'field stars: {len(field)}, named: {len(named)} (proper names: {n_named_proper})')

    with open(os.path.join(OUT, 'data-stars.js'), 'w') as f:
        f.write('// Generated by scripts/build_catalog.py — HYG Stellar Database v4.4 (Astronexus)\n')
        f.write('// [raRad, decRad, mag, bv, hip] — J2000, mag <= 6.5\n')
        f.write('const FIELD = new Float32Array([')
        f.write(','.join(f'{a},{b},{c},{d},{e}' for a, b, c, d, e in field))
        f.write(']);\n')
        f.write('// [name, raRad, decRad, mag, bv, designation, distLy, spectral]\n')
        f.write('const NAMED = ')
        f.write(json.dumps(named, ensure_ascii=False))
        f.write(';\n')

    # ---- constellation line figures ----
    with open(os.path.join(DATA, 'conlines.json')) as f:
        con = json.load(f)
    segs = []
    labels = {}
    WANT_LABELS = {'Ori':'Orion','UMa':'Ursa Major','Cas':'Cassiopeia','Sco':'Scorpius','Cru':'Crux',
                   'Lyr':'Lyra','Cyg':'Cygnus','Leo':'Leo','Tau':'Taurus','Gem':'Gemini','Aqr':'Aquarius',
                   'Psc':'Pisces'}
    for feat in con['features']:
        cid = feat['id']
        pts = []
        for line in feat['geometry']['coordinates']:
            prev = None
            for ra_d, dec_d in line:
                p = (round(ra_d * math.pi / 180.0, 4), round(dec_d * math.pi / 180.0, 4))
                pts.append(p)
                if prev is not None:
                    segs.append((prev[0], prev[1], p[0], p[1]))
                prev = p
        if cid in WANT_LABELS and pts:
            cx = sum(p[0] for p in pts) / len(pts)
            cy = sum(p[1] for p in pts) / len(pts)
            labels[cid] = [WANT_LABELS[cid], round(cx, 4), round(cy, 4)]
    print(f'constellation segments: {len(segs)}, labels: {len(labels)}')
    with open(os.path.join(DATA, 'constellations.json')) as f:
        con_names = json.load(f)
    names = {feat['id']: feat['properties']['name'] for feat in con_names['features']}
    with open(os.path.join(OUT, 'data-con.js'), 'w') as f:
        f.write('// Generated — IAU constellation figures (d3-celestial, Olaf Frohn)\n')
        f.write('// CON_LINES: [ra1,dec1,ra2,dec2] in radians, J2000; CON_LABELS: [id,ra,dec]\n')
        f.write('const CON_LINES = ')
        f.write(json.dumps([[a, b, c, d] for a, b, c, d in segs]))
        f.write(';\nconst CON_LABELS = ')
        f.write(json.dumps([[cid, v[1], v[2]] for cid, v in labels.items()], ensure_ascii=False))
        f.write(';\nconst CON_NAMES = ')
        f.write(json.dumps(names, ensure_ascii=False))
        f.write(';\n')

    # ---- milky way glow polygons (simplified) ----
    with open(os.path.join(DATA, 'mw.json')) as f:
        mw = json.load(f)
    polys = []
    for feat in mw['features']:
        for poly in feat['geometry']['coordinates']:
            ring = poly[0]
            simp = [pt for i, pt in enumerate(ring) if i % 3 == 0]
            if len(simp) < 4:
                continue
            polys.append([[round(p[0] * math.pi / 180.0, 3), round(p[1] * math.pi / 180.0, 3)] for p in simp])
    total_pts = sum(len(p) for p in polys)
    print(f'mw polygons: {len(polys)}, points: {total_pts}')
    with open(os.path.join(OUT, 'data-mw.js'), 'w') as f:
        f.write('// Generated — Milky Way outline (d3-celestial, Olaf Frohn), simplified\n')
        f.write('const MW_POLYS = ')
        f.write(json.dumps(polys))
        f.write(';\n')

    # ---- constellation boundary polygons (for sun/moon constellation lookup) ----
    with open(os.path.join(DATA, 'conbounds.json')) as f:
        cb = json.load(f)
    bounds = {}
    for feat in cb['features']:
        cid = feat['id']
        rings = bounds.setdefault(cid, [])
        for ring in feat['geometry']['coordinates']:
            # NOTE: no decimation here — IAU boundaries are orthogonal staircases
            # and stride-sampling corrupts them. Quantization to 0.1° is plenty.
            pts = []
            prev = None
            for ra_d, dec_d in ring:
                ra = ra_d % 360.0
                if prev is not None:
                    while ra - prev > 180: ra -= 360
                    while ra - prev < -180: ra += 360
                pts.append((ra, dec_d)); prev = ra
            if len(pts) >= 4:
                rings.append([[round(p[0] * math.pi / 180.0, 3), round(p[1] * math.pi / 180.0, 3)] for p in pts])
    # drop empty entries (kept for duplicate-id merges like Serpens Caput/Cauda)
    bounds = {k: v for k, v in bounds.items() if v}
    print(f'constellation bounds: {len(bounds)} constellations')
    with open(os.path.join(OUT, 'data-conbounds.js'), 'w') as f:
        f.write('// Generated — IAU constellation boundaries (d3-celestial, Olaf Frohn), simplified\n')
        f.write('// RA unwrapped across the 0h seam; query with ra, ra+2pi, ra-2pi\n')
        f.write('const CON_BOUNDS = ')
        f.write(json.dumps(bounds))
        f.write(';\n')

if __name__ == '__main__':
    main()
